# This is the appspec file for CodeDeploy.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/TeamF
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user