# This is the appspec file for CodeDeploy.
version: 0.1
os: linux
files:
  - source: /
    destination: /home/ec2-user/TeamF
hooks:
  AfterInstall:
    - location: scripts/start.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/data_ingection.sh
      runas: ec2-user
