name: Golang Test

on:
  pull_request:
    branches:
      - development

jobs:
  server-test:
    name: Server Test
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./server

      - name: Get jsondiff
        run: go get github.com/Cside/jsondiff

      - name: Test code
        run: go test -v ./server/handler
